export default [
  {
    schoolId: '0170ebdf-f7b9-4e6c-b803-2c1565677699',
    name: 'Digital Workforce Development',
    nameNative: 'Digital Workforce Development',
    code: 'DWD',
    url: 'https://dwd.sala.tech',
    email: 'admin@dwd.com',
    phone: 855123456789,
    adminLastName: 'Admin',
    adminFirstName: 'DWD',
    schoolType: 'university',
    isPublic: 'f',
    address: 'Phnom Penh',
    logo: 'https://academics-bucket-sj19asxm-prod.s3.ap-southeast-1.amazonaws.com/79ef6a21-b7bc-4ffa-949a-6029ff3f4c42/79ef6a21-b7bc-4ffa-949a-6029ff3f4c42.png',
    searchData: 'dwd digital workforce development phnom penh',
    status: 'inactive',
    mission: '',
    vision: '',
    standOutMessage: '',
    facilities: '',
    google_map: '',
    facebook: '',
    instagram: '',
    twitter: '',
    images: '',
    categories: '[]',
    videos: '',
    tuitionFees: '',
    programs: '',
    menus: '',
    seoDescription: '',
    gallery: '',
    scholarshipOverview: '',
    scholarships: '',
    exchange: '',
    website: '',
    onlineAdmission: 'f',
    requirement: '',
    createdAt: '2023-08-03 09:50:00.396+00',
    updatedAt: '2024-05-14 07:58:22.038432+00',
    field: '',
    overview:
      '<p>The USAID Digital Workforce Development project in Cambodia (USAID DWD) is a five-year (2021-2026) project funded by the USAID, implemented by the University of California at Berkeley in partnership with ELIX Organization and The Asia Foundation.&nbsp;</p>\n\n<p>USAID DWD equips young Cambodians with the skills and resources to succeed in the digital era by employing a multifaceted ecosystem approach. By empowering Higher Education Institutions (HEIs) with the resources and knowledge to enhance ICT education and teaching. USAID DWD supports youth to be workforce-ready through upskilling and career guidance, and leverages the private sector to collaborate with HEIs under the shared objective of providing capacity building, employment support and opportunities for the youth.&nbsp;</p>\n\n<p>The career centers launched under USAID DWD were launched at 5 partnering HEI(s) across the country at: the National University of Battambang, the National University of Management, Cambodia Academy of Digital Technology and the University of South-East Asia.&nbsp;</p>\n\n<p>The career centers were created to connect youth to job/internship opportunities, career guidance, capacity building and more, with the ultimate goal of supporting young talent to join the workforce and empowering them to pursue their desired career paths.</p>\n',
    overviewKhmer: '',
    tuition_fee: '',
    tuition_fee_khmer: '',
    program_english: '',
    program_khmer: '',
    scholarshipsKhmer: '',
    exchangePrograms: '',
    exchangeProgramsKhmer: '',
    archiveStatus: 0,
  },
]
